name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        ruby-version: ['4.0']

    steps:
    - uses: actions/checkout@main
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - run: bin/radd setup --config test/radd.yml
    - run: bin/radd add --config test/radd.yml < test/add.input
    - run: bin/radd start --config test/radd.yml & echo -n $! > radd.pid
    - run: bundle exec ruby test/radd_test.rb
    - run: kill `cat radd.pid`
